### ISSUE TITLE
Conda package.

### ISSUE THREAD

**Issue by leobiscassi** [rodrigofaccioli/2pg_cartesian#3]
Hi @rodrigofaccioli, can you please create a new release (ie. v1.0) of the project? I'm working to support this project on a conda package and for this I need of the one link to a version. The version "CASP_11" no makes sense for me, what do you think about it?
I suggest you normalize the releases, for example, v1.0, v1.1 ... v2.0, etc. Let me know what you think.

**Comment by rodrigofaccioli** [comment]
Hi @leobiscassi, thanks your suggestion for creating of project version. 
I will do it until tomorrow. Please, can we talk of 2PG version at hangout?

**Comment by leobiscassi** [comment]
sure! :smiley:

**Comment by leobiscassi** [comment]
Thanks @rodrigofaccioli !
